version: '3.8'

services:
  postgres_auth:
    container_name: auth_postgres_container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  postgres_dummy:
    container_name: dummy_postgres_container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pg_dummy_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  redis_auth:
    container_name: auth_redis_container
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6379:6379"
    volumes:
      - redis_auth_data:/data

  redis_dummy:
    container_name: dummy_redis_container
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6380:6379"
    volumes:
      - redis_dummy_data:/data

volumes:
  pg_auth_data:
  pg_dummy_data:
  redis_auth_data:
  redis_dummy_data:
