version: '3.8'

networks:
  main_network:
    external: true

services:
  app:
    container_name: AuthService
    image: ${IMAGE}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: "postgres"
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: "redis"
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PORT: ${PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_EXCHANGES: ${RABBITMQ_EXCHANGES}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - main_network

  postgres:
    container_name: ${POSTGRES_CONTAINER}
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - main_network

  redis:
    container_name: ${REDIS_CONTAINER}
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - main_network

volumes:
  pg_data:
  redis_data:
